# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  artifact-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: |
          go get .
      - name: Build linux
        run: |
          go build -o biliAutoBlackList-linux-amd64
      - uses: actions/upload-artifact@v4.3.3
        with:
          path: biliAutoBlackList-linux-amd64
