# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  artifact-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
        include:
          - os: ubuntu-20.04
            build-name: linux
          - os: windows-latest
            build-name: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: |
          go get .
      - name: Build darwin
        if: matrix.os == 'windows-latest'
        run: |
          go build -o biliAutoBlackList-${{ matrix.build-name }}-amd64
      - name: Build linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          go build -o biliAutoBlackList-${{ matrix.build-name }}-amd64
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: biliAutoBlackList-${{ matrix.build-name }}-amd64
          path: biliAutoBlackList-${{ matrix.build-name }}-amd64

